### ISSUE TITLE
[BUG] use of `set` as class attribute type causes exception

### ISSUE THREAD

**Issue by JoeHCQ1** [mkdocstrings/pytkdocs#139]
**Describe the bug**
If you define a class attribute's type as `set` pytkdocs crashes.

**To Reproduce**
```python
class Example:
    """The example class is a stand-in class for illustration"""

    my_legal_attribute: List[str]

    my_illegal_attribute: set[str]
```

**Expected behavior**
`pytkdocs` would parse the attributes without breaking.

**Error text**
```
ERROR    -  mkdocstrings: 'type' object is not subscriptable
            Traceback (most recent call last):
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/cli.py", line 114, in process_json
                return process_config(json.loads(json_input))
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/cli.py", line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/loader.py", line 358, in get_object_documentation
                root_object = self.get_module_documentation(leaf, members)
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/loader.py", line 426, in get_module_documentation
                root_object.add_child(self.get_class_documentation(child_node))
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/loader.py", line 483, in get_class_documentation
                merge(attributes_data, get_class_attributes(parent_class))
              File "/home/user/repo/avenv/lib/python3.8/site-packages/pytkdocs/parsers/attributes.py", line 115, in get_class_attributes
                type_hints = get_type_hints(cls)
              File "/usr/lib/python3.8/typing.py", line 1232, in get_type_hints
                value = _eval_type(value, base_globals, localns)
              File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
                return t._evaluate(globalns, localns)
              File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
                eval(self.__forward_code__, globalns, localns),
              File "<string>", line 1, in <module>
            TypeError: 'type' object is not subscriptable
ERROR    -  Error reading page 'reference/api/Example.md':
ERROR    -  Could not collect 'repo.Example'
```

**System (please complete the following information):**
- `pytkdocs` version: 0.16.1
- Python version: 3.8
- OS: Linux

**Workaround:**

```python
class Example:
    """The example class is a stand-in class for illustration"""

    my_legal_attribute: List[str]

    # my_illegal_attribute: set[str]
    my_illegal_attribute = set()
```

**Comment by pawamoy** [comment]
A few questions:

- I believe you're using Python 3.8, can you confirm?
- do you actually `from __future__ import annotations` which allows using types as subscriptable objects?
- can you see if #113 fixes it locally? it's a single line to add to pytkdocs/loader.py :slightly_smiling_face:

**Comment by JoeHCQ1** [comment]
I can confirm I am using Python 3.8.

I am using `from __future__ import annotations`.

I tried your fix, which, added the line to my `loader.py` file like so:
![image](https://user-images.githubusercontent.com/49208786/157319225-5a852d79-6e93-463b-a239-38b5911e1c9f.png)

And tried again, unfortunately I got the same error. ☹️ 

I've had vs-code not save when I thought it did sometimes so I verified that the change was there via `head  ./avenv/lib/python3.8/site-packages/pytkdocs/loader.py` and it was in fact there, just not helping.

Thanks though 🙂

**Comment by pawamoy** [comment]
I can confirm that `get_type_hints` simply does not support future annotations on Python less than 3.9. So I'm inclined to say that the pytkdocs + future annotations combo is not supported on Python less than 3.9 :confused: 
If you feel like something could be improved in the code (to bring support or at fail gracefully), please do open a PR, I will review it.

**Comment by JoeHCQ1** [comment]
Thanks for looking into this @pawamoy! I don't have any recommended changes.
