### ISSUE TITLE
[BUG?] wxPython breaks mkdocstrings

### ISSUE THREAD

**Issue by BalduinLandolt** [mkdocstrings/pytkdocs#84]
**Describe the bug**
When trying to document a project using wxPython, mkdocstrings breaks.  
(I don't know if the issue actually belongs here, or rather is a mkdocstrings issue or a wxPython problem. Sorry!)  
I get the following error message:
```shell
mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/balduin/Desktop/mktest/site 
ERROR   -  mkdocstrings.handlers.python: Collection failed: 'sip'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/loader.py", line 340, in get_object_documentation
    root_object = self.get_module_documentation(leaf, members)
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/loader.py", line 407, in get_module_documentation
    root_object.add_child(self.get_class_documentation(child_node))
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/loader.py", line 439, in get_class_documentation
    merge(attributes_data, get_class_attributes(parent_class))
  File "/usr/local/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 130, in get_class_attributes
    type_hints = get_type_hints(cls)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1345, in get_type_hints
    base_globals = sys.modules[base.__module__].__dict__
KeyError: 'sip'
 
ERROR   -  mkdocstrings.extension: Could not collect 'src.main' 
ERROR   -  Error reading page 'reference/main.md': 'sip' 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/extension.py", line 155, in run
    xml_element = self.process_block(identifier, str(block))
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/extension.py", line 194, in process_block
    data: Any = handler.collector.collect(identifier, selection)
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/handlers/python.py", line 221, in collect
    raise CollectionError(error)
mkdocstrings.handlers.CollectionError: 'sip'
```

**To Reproduce**
The above error message comes from a (mostly) minimal example I used for testing myself:
```
./
|- src/
   |- main.py
|- docs/
   |- reference/
      |- main.md
   |- index.md
|- README.md
|- mkdocs.yml
```
Where `index.md` simply points to the readme, and the `.yml` sets up all the mkdocs and mkdocstrings stuff.

When `main.py` looks as follows, all works as expected:
```python
"""
This is the main module
"""
import wx

class Main(object):
# class Main(wx.Frame):
    """
    This is the main class
    """
    pass
```
When I change the following two lines, I get said error:
```python
# class Main(object):
class Main(wx.Frame):
```
So, I think it's pretty cleat that the setup is ok and the error happens when I start using wxPython stuff.

**Expected behavior**
No error?

**Screenshots**
None

**System (please complete the following information):**
- `pytkdocs` version: 0.9.0
- `mkdocs`: 1.1.2
- `mkdocstrings`: 0.13.6
- `wxPython`: 4.1.0
- Python version: 3.9.0
- OS: MacOS

**Comment by pawamoy** [comment]
Hello @BalduinLandolt, thank you for the report!

It seems to me that the combo wxPython and [`get_type_hints`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) is at fault here. So at first glance I'd say there's not much we can do on pytkdocs side. Did you search in Python's bugtracker to see if you can find something similar?

**Comment by BalduinLandolt** [comment]
Indeed so: https://bugs.python.org/issue41515  
I guess that can be closed then, sorry

**Comment by pawamoy** [comment]
No problem! Thank you for searching and finding the Python issue :slightly_smiling_face: 
I'll keep it open because we could catch the KeyError while waiting for the fix.

**Comment by pawamoy** [comment]
The linked bpo is resolved, closing! Unless the fix still didn't land, in this case please reopen
