### ISSUE TITLE
[BUG] AttributeError: 'Name' object has no attribute 'value' (again)

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/pytkdocs#92]
**Describe the bug**
```
ERROR   -  mkdocstrings.handlers.python: Collection failed: 'Name' object has no attribute 'value'
Traceback (most recent call last):
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py", line 342, in get_object_documentation
    root_object = self.get_module_documentation(leaf, members)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py", line 409, in get_module_documentation
    root_object.add_child(self.get_class_documentation(child_node))
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py", line 445, in get_class_documentation
    attributes_data.update(get_instance_attributes(class_.__init__))
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 160, in get_instance_attributes
    annotation = node_to_annotation(assignment)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 24, in node_to_annotation
    return f"{value_id}[{node_to_annotation(value)}]"
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 30, in node_to_annotation
    annotations = [node_to_annotation(n) for n in node.elts]
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 30, in <listcomp>
    annotations = [node_to_annotation(n) for n in node.elts]
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/mkdocstrings-ytlBmpdO-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 28, in node_to_annotation
    return f"{node.value.id}[{node_to_annotation(node.slice.value)}]"  # type: ignore
AttributeError: 'Name' object has no attribute 'value'
```

**To Reproduce**
On latest mkdocstrings or pytkdocs repositories with Python 3.9.

**Expected behavior**
No error.

**System (please complete the following information):**
- `pytkdocs` version 0.10.1
- Python version: 3.9
- OS: Linux

**Additional context**
I thought this was fixed, but apparently not...
#73, #75 and https://github.com/pawamoy/pytkdocs/commit/ae80e988edf362ce99a880063639e4cd74bc44bb (indeed line 28 was not touched)

**Comment by jnoortheen** [comment]
I am also getting similar error with py39 
```
ERROR   -  mkdocstrings.handlers.python: Collection failed: 'Attribute' object has no attribute 'id'
Traceback (most recent call last):
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py", line 344, in get_object_documentation
    root_object = self.get_class_documentation(leaf, members)
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py", line 445, in get_class_documentation
    attributes_data.update(get_instance_attributes(class_.__init__))
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 163, in get_instance_attributes
    annotation = node_to_annotation(assignment)
  File "/home/noor/.virtualenvs/arger-eQ89_dRb-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py", line 22, in node_to_annotation
    value_id = node.annotation.value.id  # type: ignore
AttributeError: 'Attribute' object has no attribute 'id'

```

**Comment by pawamoy** [comment]
@jnoortheen thank you for reporting as well. Could help even further and provide me with code that will reproduce the error?

**Comment by jnoortheen** [comment]
> @jnoortheen thank you for reporting as well. Could help even further and provide me with code that will trigger the error in pytkdocs? A link to a public repo is fine

I was using the latest version with this repo https://github.com/jnoortheen/arger . It worked after downgrading pytkdocs.
